variables:
  LD_LIBRARY_PATH: /usr/local/lib

trigger: ['master']

jobs:
  - job: osx_64
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 20
    pool:
      vmImage: macOS-10.13
    strategy:
      matrix:
        fgsl_nogui_noocl:
          EXTRA: --disable-gui --disable-updater --disable-opencl
          HOMEBREW_EXTRA: gsl
          USE_FGSL: True
        fgsl_nogui_ocl:
          EXTRA: --disable-gui --disable-updater --enable-opencl
          HOMEBREW_EXTRA: gsl
          USE_FGSL: True
        easyrng_nogui_noocl:
          EXTRA: --disable-gui --disable-updater --disable-opencl
          USE_EASYRNG: True
        easyrng_nogui_ocl:
          EXTRA: --disable-gui --disable-updater --enable-opencl
          USE_EASYRNG: True
        easyrng_gui_noupdater_noocl_noga:
          EXTRA: --enable-gui --disable-updater --disable-opencl --disable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot
        easyrng_gui_updater_noocl_noga:
          EXTRA: --enable-gui --enable-updater --disable-opencl --disable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot json-glib
        easyrng_gui_noupdater_ocl_noga:
          EXTRA: --enable-gui --disable-updater --enable-opencl --disable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot
        easyrng_gui_updater_ocl_noga:
          EXTRA: --enable-gui --enable-updater --enable-opencl --disable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot json-glib
        easyrng_gui_noupdater_noocl_ga:
          EXTRA: --enable-gui --disable-updater --disable-opencl --enable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot
        easyrng_gui_updater_noocl_ga:
          EXTRA: --enable-gui --enable-updater --disable-opencl --enable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot json-glib
        easyrng_gui_noupdater_ocl_ga:
          EXTRA: --enable-gui --disable-updater --enable-opencl --enable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot
        easyrng_gui_updater_ocl_ga:
          EXTRA: --enable-gui --enable-updater --enable-opencl --enable-google-analytics
          USE_EASYRNG: True
          HOMEBREW_EXTRA: tschoonj/tap/gtkmm-plplot json-glib
      
      
    steps:
    - script: |
        set -e -x
        brew uninstall --force --ignore-dependencies $(brew list) || exit 1
        brew update
        brew cleanup -s
      displayName: Remove all Homebrew packages
    - script: |
        set -e -x
        brew install autoconf automake libtool wget pkg-config libxslt hdf5 libsoup pygobject3 bash swig numpy gcc llvm librsvg
        pip3 install lxml
      displayName: Install shared Homebrew dependencies

    - script: |
        set -e -x
        brew install $HOMEBREW_EXTRA
      displayName: Install extra Homebrew dependencies
      condition: ne(variables['HOMEBREW_EXTRA'], '')

    - script: |
        set -e -x
        wget http://www.lrz.de/services/software/mathematik/gsl/fortran/download/fgsl-1.2.0.tar.gz
        tar xfz fgsl-1.2.0.tar.gz
        cd fgsl-1.2.0
        ./configure --disable-static
        make
        sudo make install
        cd ..
      displayName: Install FGSL
      env:
        CC: /usr/local/opt/llvm/bin/clang
        CXX: /usr/local/opt/llvm/bin/clang++
        FC: gfortran
      condition: eq(variables['USE_FGSL'], True)

    - script: |
        set -e -x
        wget https://github.com/tschoonj/easyRNG/releases/download/easyRNG-1.1/easyRNG-1.1.tar.gz
        tar xfz easyRNG-1.1.tar.gz
        cd easyRNG-1.1
        ./configure --enable-fortran --disable-static
        make -j2
        sudo make install
        cd ..
      displayName: Install easyRNG
      env:
        CC: /usr/local/opt/llvm/bin/clang
        CXX: /usr/local/opt/llvm/bin/clang++
        FC: gfortran
      condition: eq(variables['USE_EASYRNG'], True)

    - script: |
        set -e -x
        git clone --single-branch --depth=1 https://github.com/tschoonj/xraylib.git
        cd xraylib 
        autoreconf -fi
        ./configure --disable-perl --disable-ruby --enable-fortran2003 --disable-static --enable-python PYTHON=/usr/local/bin/python3 --enable-python-integration
        make -j2
        make install
        cd ..
      displayName: Install xraylib
      env:
        CC: /usr/local/opt/llvm/bin/clang
        CXX: /usr/local/opt/llvm/bin/clang++
        FC: gfortran

    - script: |
        set -e -x
        autoreconf -fi
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig
        ./configure $EXTRA --disable-static --enable-introspection PYTHON=/usr/local/bin/python3 SHELL=/usr/local/bin/bash
        make
        make check
      displayName: Test build
      env:
        CC: /usr/local/opt/llvm/bin/clang
        CXX: /usr/local/opt/llvm/bin/clang++
        FC: gfortran
        OBJC: /usr/local/opt/llvm/bin/clang
        LIBS: -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib

    - script: |
        cd tests
        cat test*.log
      displayName: Print test
      condition: failed()
