version: 2.1
commands:
        full_build:
                description: "Full build including make distcheck"
                parameters:
                        EXTRA:
                                type: string
                steps:
                        - checkout
                        - run: autoreconf -fi
                        - run: ./configure << parameters.EXTRA >> --enable-custom-detector-response --disable-static --enable-introspection --enable-silent-rules
                        - run: make
                        - run:
                                command: make distcheck
                                no_output_timeout: 30m
jobs:
        # xenial: fgsl and gtkmm-plplot
        # no updater
        # with gui
        job1:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-fgsl.with-gtkmm-plplot.disable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui --disable-updater"
        # xenial: fgsl and gtkmm-plplot
        # with updater
        # with gui
        job2:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-fgsl.with-gtkmm-plplot.enable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui -enable-updater"
        # xenial: fgsl
        # no updater
        # no gui
        job3:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater"
        # xenial: easyRNG and gtkmm-plplot
        # no updater
        # with gui
        job4:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-easyRNG.with-gtkmm-plplot.disable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui --disable-updater"
        # xenial: easyRNG and gtkmm-plplot
        # with updater
        # with gui
        job5:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-easyRNG.with-gtkmm-plplot.enable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui --enable-updater"
        # xenial: easyRNG
        # no updater
        # no gui
        job6:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-easyRNG.without-gtkmm-plplot.disable-updater.disable-gui"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater"
        # centos7: fgsl and gtkmm-plplot
        # no updater
        # with gui
        # with google-analytics
        job7:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:centos7.with-fgsl.with-gtkmm-plplot.disable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui --disable-updater --enable-google-analytics"
        # centos7: fgsl and gtkmm-plplot
        # with updater
        # with gui
        # with google-analytics
        job8:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:centos7.with-fgsl.with-gtkmm-plplot.enable-updater.enable-gui"
                steps:
                        - full_build:
                                EXTRA: "--enable-gui --enable-updater --enable-google-analytics"
        # centos7: fgsl
        # no updater
        # no gui
        # with google-analytics
        job9:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:centos7.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater --enable-google-analytics"
        # xenial: fgsl
        # no updater
        # no gui
        # with MPI
        job10:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater --enable-mpi"
        # xenial: easyRNG
        # no updater
        # no gui
        # with MPI
        job11:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:xenial.with-easyRNG.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater --enable-mpi"
        # centos7: easyRNG
        # no updater
        # no gui
        # with google-analytics
        # with MPI
        job12:
                docker:
                        - image: "tomschoonjans/xmimsim-travis-ci:centos7.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi"
                steps:
                        - full_build:
                                EXTRA: "--disable-gui --disable-updater --enable-mpi --enable-google-analytics"
                environment:
                        MPICC: "/usr/lib64/openmpi/bin/mpicc"

workflows:
        workflow:
                jobs:
                        - job1
                        - job2
                        - job3
                        - job4
                        - job5
                        - job6
                        - job7
                        - job8
                        - job9
                        - job10
                        - job11
                        - job12
